# Generated by Django 5.0.6 on 2024-07-21 15:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyumonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(default=datetime.datetime(2024, 7, 22, 0, 47, 30, 672306))),
                ('checkout', models.DateTimeField(default=datetime.datetime(2024, 7, 22, 0, 47, 30, 672306))),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'hotel_name',
            },
        ),
        migrations.CreateModel(
            name='HotelPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='hotel_pictures/')),
                ('order', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelname')),
            ],
            options={
                'db_table': 'hotel_pictures',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('people', models.IntegerField()),
                ('room_type', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hotel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelname')),
            ],
            options={
                'db_table': 'plan_name',
            },
        ),
    ]
