# Generated by Django 5.0.6 on 2024-07-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'hotel_name',
            },
        ),
        migrations.CreateModel(
            name='PlanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('people', models.IntegerField()),
                ('price', models.IntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelname')),
            ],
            options={
                'db_table': 'plan_name',
            },
        ),
        migrations.CreateModel(
            name='HotelPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='hotel_pictures/')),
                ('order', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.planname')),
            ],
            options={
                'db_table': 'hotel_pictures',
                'ordering': ['order'],
            },
        ),
    ]
