# Generated by Django 5.0.6 on 2024-07-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planname',
            name='room_type',
            field=models.CharField(max_length=1000),
        ),
    ]
