# Generated by Django 5.0.6 on 2024-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planname',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
