# Generated by Django 5.0.6 on 2024-08-07 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_planname_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresses',
            name='checkin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='checkout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
