# Generated by Django 5.0.6 on 2024-07-22 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_cyumoninfo_checkin_alter_cyumoninfo_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelname',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='hotelname',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 1, 10, 41, 655496)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 1, 10, 41, 655496)),
        ),
    ]
