# Generated by Django 5.0.6 on 2024-07-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_planname_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpictures',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelname'),
        ),
    ]
