# Generated by Django 5.0.6 on 2024-07-22 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotelname_options_hotelname_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planname',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='planname',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 1, 49, 48, 66641)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 1, 49, 48, 66641)),
        ),
    ]
