# Generated by Django 5.0.6 on 2024-08-07 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_useraddresses_checkin_useraddresses_checkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraddresses',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='useraddresses',
            unique_together={('last_name', 'first_name', 'zip_code', 'address', 'phone_number', 'user', 'checkin', 'checkout')},
        ),
    ]
