# Generated by Django 5.0.6 on 2024-07-23 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_planname_options_planname_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planname',
            name='picture',
            field=models.FileField(null=True, upload_to='hotel_pictures/'),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 0, 25, 55, 14457)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 0, 25, 55, 14457)),
        ),
    ]
