# Generated by Django 5.0.6 on 2024-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_cartitems_kupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='planname',
            name='plan_id',
            field=models.IntegerField(default=0),
        ),
    ]
