# Generated by Django 5.0.6 on 2024-07-23 16:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_planname_picture_alter_cyumoninfo_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 1, 9, 47, 973594)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 1, 9, 47, 973594)),
        ),
        migrations.CreateModel(
            name='PlanPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plan_pictures/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='hotel.planname')),
            ],
        ),
    ]
