# Generated by Django 5.0.6 on 2024-07-24 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_cyumoninfo_checkin_alter_cyumoninfo_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planname',
            name='picture',
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 19, 51, 25, 605556)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 19, 51, 25, 605556)),
        ),
        migrations.AlterField(
            model_name='planpictures',
            name='image',
            field=models.ImageField(upload_to='hotel_pictures/'),
        ),
    ]
