# Generated by Django 5.0.6 on 2024-07-24 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_planname_picture_alter_cyumoninfo_checkin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planpictures',
            options={'ordering': ['plan', 'order'], 'verbose_name': 'Plan Picture', 'verbose_name_plural': 'Plan Pictures'},
        ),
        migrations.AddField(
            model_name='planpictures',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 20, 16, 32, 501015)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 20, 16, 32, 501015)),
        ),
        migrations.AlterField(
            model_name='planpictures',
            name='image',
            field=models.ImageField(upload_to='plan_pictures/'),
        ),
    ]
