# Generated by Django 5.0.6 on 2024-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_orders_kupon_amount_alter_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
