# Generated by Django 5.0.6 on 2024-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_cartitems_checkin_cartitems_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
