# Generated by Django 5.0.6 on 2024-07-24 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_carts_alter_cyumoninfo_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 0, 6, 18, 375432)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 0, 6, 18, 375432)),
        ),
    ]
