# Generated by Django 5.0.6 on 2024-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_room_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
