# Generated by Django 5.0.6 on 2024-07-24 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_cyumoninfo_checkin_alter_cyumoninfo_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='planname',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 0, 28, 12, 82749)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 0, 28, 12, 82749)),
        ),
    ]
