# Generated by Django 5.0.6 on 2024-07-25 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_planname_stock_alter_cyumoninfo_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 23, 3, 30, 529954)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 23, 3, 30, 529954)),
        ),
        migrations.AlterField(
            model_name='hotelpictures',
            name='image',
            field=models.FileField(null=True, upload_to='hotel_pictures/'),
        ),
        migrations.AlterField(
            model_name='planpictures',
            name='image',
            field=models.FileField(upload_to='plan_pictures/'),
        ),
    ]
