# Generated by Django 5.0.6 on 2024-08-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_orderitems_address_orderitems_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
