# Generated by Django 5.0.6 on 2024-07-29 13:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_cyumoninfo_checkin_alter_cyumoninfo_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planname',
            name='checkin',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='planname',
            name='checkout',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cyumoninfo',
            name='checkout',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='planname',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='PlanListCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.planname')),
            ],
        ),
    ]
