# Generated by Django 5.0.6 on 2024-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_planname_checkin_planname_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planname',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planname',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
