# Generated by Django 5.0.6 on 2024-07-13 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="電話番号は'090-1234-5678'の形式、もしくは数字11桁で入力してください。", regex='^(\\d{3}-\\d{4}-\\d{4}|\\d{11})$')], verbose_name='電話番号')),
                ('zip_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="郵便番号は'123-4567'の形式、もしくは数字7桁で入力してください。", regex='^(\\d{3}-\\d{4}|\\d{7})$')], verbose_name='郵便番号')),
            ],
        ),
    ]
