# Generated by Django 5.0.6 on 2024-07-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_samplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
